### ISSUE TITLE
Is it possible to make slider?

### ISSUE THREAD

**Issue by muslimpergics** [miromanestar/Youtube-Gallery#1]
Hi there
Is it possible to make slider?

Thanks for the library, it saves me a lot of time

**Comment by miromanestar** [comment]
It is possible, but would require some modifications to be made to the script.
I'd look into using the [Swiper](https://swiperjs.com/) library and integrating it with my script.

I might add this myself in the future as it is a great idea, but I'm not planning on doing so anytime soon.
