### ISSUE TITLE
What is playlistId?

### ISSUE THREAD

**Issue by IN80** [miromanestar/Youtube-Gallery#2]
Hello. I do not quite understand where to get this **playlistId**. In your demo, I understand that you have different videos. How does it work? After all, he takes information from the YouTube channel, or am I misunderstanding something?

**Comment by IN80** [comment]
I found: https://www.youtube.com/playlist?list=PL4BrNFx1j7E6a6IKg8N0IgnkoamHlCHWa

Tell me, can the same thing be done only for the whole channel, without creating a separate playlist for it?

**Comment by miromanestar** [comment]
In the script's current incarnation, it only retrieves videos from a given playlist as opposed to a channel. Accessing all the videos from a channel would require using an API endpoint this script simply doesn't use.
That being said, it's completely possible to modify the script yourself to grab videos from the entire channel. Or, as you mentioned, you could create a playlist and add all the channel's videos to it.
